### ISSUE TITLE
API call not recognized

### ISSUE THREAD

**Issue by BouweCeunen** [siacentral/host-dashboard#4]
I have a docker-compose.yml file.
I've built the `siad` and `sia-dashboard` images myself from the repositories of siacentral.
```
services:
  sia:
    image: siad
    volumes:
    - shared:/sia-data
    ports: 
    - "127.0.0.1:9980:9980"
    - "9981:9981"
    - "9982:9982"
    environment:
    - SIA_MODULES=cghrtw
  sia-dashboard:
    image: sia-dashboard
    depends_on:
    - sia
    links:
    - sia
    environment:
    - SIA_API_ADDR=sia:9980
    volumes:
    - shared:/sia-data
version: '2.1'
volumes:
  shared: {}
```

But I'm getting following errors.

```
[11/04/20 3:02:28] ➜  host-dashboard git:(master) ✗ docker-compose up
Recreating sia-renter_sia_1 ... done
Recreating sia-renter_sia-dashboard_1 ... done
Attaching to sia-renter_sia_1, sia-renter_sia-dashboard_1
sia-dashboard_1  | 2020/04/11 01:02:39 daemon.go:39: Starting Host Dashboard v0.0.4
sia-dashboard_1  | 2020/04/11 01:02:39 daemon.go:39: Revision:  Build Time: 
sia-dashboard_1  | 2020/04/11 01:02:39 daemon.go:39: SiaAddr: sia:9980
sia_1            | A secure API password has been written to /root/.sia/apipassword
sia_1            | This password will be used automatically the next time you run siad.
sia_1            | Sia Daemon v1.4.7
sia_1            | Git Revision a578a7e4e
sia_1            | Loading...
sia-dashboard_1  | 2020/04/11 01:02:39 sync.go:138: warn: unable to retrieve bandwidth: [failed to get reader response; unable to perform GET on /host/bandwidth; API call not recognized]
sia-dashboard_1  | 2020/04/11 01:02:39 daemon.go:120: error syncing data: refreshing contracts: get sia contracts: [failed to get reader response; unable to perform GET on /host/contracts; API call not recognized]
sia_1            | (1/7) Loading siad...
sia_1            | (2/7) Loading gateway...
sia_1            | (3/7) Loading consensus...
sia_1            | (4/7) Loading transaction pool...
sia_1            | (5/7) Loading wallet...
sia_1            | (6/7) Loading host...
sia_1            | (7/7) Loading renter...
sia_1            | API is now available, synchronous startup completed in 0.747 seconds
sia-renter_sia-dashboard_1 exited with code 1
```

If I add `restart: on-failure` in the docker-compose.yml, it says the following.
```
sia-dashboard_1  | 2020/04/11 01:13:29 daemon.go:120: error syncing data: refreshing connectivity: unable to parse netaddress
sia-renter_sia-dashboard_1 exited with code 1
```
I checked that I start the renter module on said. What could be the issue?
